services:
  - type: web
    name: repository-mirror
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -k uvicorn.workers.UvicornWorker -w 4 -b 0.0.0.0:10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GITHUB_TOKEN
        sync: false
